### ISSUE TITLE
Adding Medias view to MetadataViews.NFTView

### ISSUE THREAD

**Issue by bymi15** [onflow/flow-nft#123]
## Issue To Be Solved

Are there any reasons why the `Medias` view is not included in the `MetadataViews.NFTView`?
Can this be included as there are quite a few NFT collections that use video files rather than images and this can only be included in the `Medias` view.

**Comment by bjartek** [comment]
We cannot add state to this struct as it is already created, then you would need to have a new version of the view with a new name.

**Comment by bymi15** [comment]
I’m guessing that’s due to the limitation of flow contract updatability.
In that case, NFTViewV2 sounds like the way to go. 
Maybe there should be some further discussions on other areas of improvements before deciding what needs to be added to V2.

**Comment by joshuahannan** [comment]
@bymi15 Can you open a PR with this update? That would be a good place to have this discussion

**Comment by bymi15** [comment]
> @bymi15 Can you open a PR with this update? That would be a good place to have this discussion

Thanks for your response @joshuahannan
I have just raised a PR as you've suggested.

**Comment by PeterBenc** [comment]
IMO this is quite an important issue, as far I understand it, the only source of `Media` for a single nft is the `thumbnail` field which isn't of type `Media` (honestly its pretty strange that colleciton-specific data had media files but nfts don't). I was hoping we could migrate from alchemy to nft catalog but since all I have is `a thumbnail` of which I don't even know what `mimeType` it is I really can't :( 

Pls correct me if I am wrong but seems like as long nft media goes, the `thumbnail` field is the best I can do right now.

**Comment by bymi15** [comment]
@PeterBenc I think the `thumbnail` field was intended more for small-medium sized images that can be displayed on websites.
Totally agree that there should be a field that allows one or more media files (i.e. the `medias` view should be included in the core NFTView)

**Comment by joshuahannan** [comment]
As we said in the PR, the NFTView is not a requirement, it is simply a utility view that combines all other views. If you want `Medias` to be included in a whole view, you can simply define a view in your script that combines `Medias` with `NFTView` and return that. I don't think we're at the point yet where we want to define a new NFTView. I'm tempted to just close this issue

**Comment by bymi15** [comment]
The problem is that this is all tied in with NFTCatalog which uses NFTView: https://github.com/dapperlabs/nft-catalog/blob/main/cadence/contracts/NFTRetrieval.cdc#L99

Perhaps this could be raised in NFTCatalog - so they can support other metadata views such as Medias, then we could probably close this one.

**Comment by bymi15** [comment]
@bshahid331 yeah that's true but I think it would be nice to include other views in `getNFTViewsFromCap`. Otherwise, we would have to write our own custom script to get the other views such as `Medias` and `getNFTViewsFromCap` would not be used at all.

**Comment by PeterBenc** [comment]
Thanks for the discussion, I dug a bit deeper and realized I was missing some context in order to comprehend this fully, So I found out I should be able to get other media files and not rely on the `thumbnail` filed alone, but as @bymi15 said, I ll need to write my own version of `getNFTViewsFromCap`. Which is fine I guess. Not sure why `Medias` were excluded from the `NFTView` which lead us all here :smile: but I suppose this issue is resolved (at least for me). :+1:

**Comment by bymi15** [comment]
@PeterBenc 
Great. I’m glad it’s all sorted out for you.
So i guess i’m going to close this issue since there shouldn’t be any blockers due to this.
