### ISSUE TITLE
Flow NFT contracts do not implement a standard way to name their public collection path

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-nft#157]
## Instructions

Given:
- The contract name and address (`0x0b2a3299cc857e29`, `TopShot`)
- The NFT token ID (`1234`)
- The Owner address (`0x01`)

Determine:
- NFT metadata using metadata views

### Problem
In the below example the `CollectionPublicPath ` might not exists in the contract.
```
  let collection = account
        .getCapability(ExampleNFT.CollectionPublicPath)
        .borrow<&{MetadataViews.ResolverCollection}>()
        ?? panic("Could not borrow a reference to the collection")
```
Example `TopShot` uses a different name for that variable.

### Context

Also, the NFT Catalog does not have a simple way to fetch the metadata of a single NFT when only the data above is known.

**Comment by cybercent** [comment]
https://github.com/dapperlabs/nft-catalog/issues/121

**Comment by joshuahannan** [comment]
Thanks for sharing! So when we originally created the NFT standard, it wasn't possible to have paths as variables, so we weren't able to include a path requirement in the `NonFungibleToken.Vault` definition. As you probably know, upgrades are difficult in that we can't add paths to existing types, so adding these requirements on their own isn't really possible. 

Additionally, the metadata views have a view to get the paths in the [`NFTCollectionData` view](https://github.com/onflow/flow-nft/blob/master/contracts/MetadataViews.cdc#L484), so projects can decide how they would like to store them and they can use the standard view to share them. 

I do acknowledge that is is difficult to get metadata about an NFT without the paths though, but I'm not sure what we could do to have a standard for this in the short term since we can't add a path field requirement to the NFT standard without breaking every contract. 

[We do have a change that addresses this in the NFT standard V2 though](https://github.com/onflow/flow-nft/pull/126/files#diff-aeae1d8aa0fb3d982e39a67e1a9c86476c35844f609565bf06a0a383e0acefd9R271), which will include breaking changes and will come later this year assuming we get enough buy-in from the community.
I'd recommend reading through those changes and leaving feedback, because we definitely could use the help. 🙂 

Besides that, is there another option that you think we could do to make this easier?

**Comment by joshuahannan** [comment]
Closing this because it is addressed with metadata views and the NFT V2 standard
