### ISSUE TITLE
DictView

### ISSUE THREAD

**Issue by austinkline** [onflow/flow-nft#73]
### Issue To Be Solved
A generic platform supporting any resource implementing the NFT standard has no view to use which contains all metadata for a given NFT. For example, TopShot uses the [TopShotMomentMetadataView](https://github.com/dapperlabs/nba-smart-contracts/blob/master/contracts/TopShot.cdc#L462). However, for platforms such as flowty to use it, we must know when to ask for TopShot's metadata view versus another collection's own view should they also implement the nft standard. Additionally, platforms consuming these views would need to know how to read the resulting type which would necessitate importing that type and adding code into our own contracts that interpret them.

As more and more collections come to flow, dapps will need a more flexible view as an option which all collections can support that will return a complete set of metadata from a given NFT. Having this proposed view will let dapps implement features which are dependent on the metadata from a given nft without needing to understand its underlying type. For instance, a marketplace might want to support global offers where a users can offer to buy an item from anyone if and only if its metadata contains certain key/value pairs such as an offer on any Topshot Moment which comes from Play X and has a Serial number less than Y.

### Suggested Solution:

@bjartek has mentioned a suggested `TagsView` which would return a `{String:String}` mapping, but I think we need a more flexible option in order to support comparison operations. The below view is what I would suggest:

```
pub struct DictView {
    pub let data: {String: AnyStruct}
}
```

**Comment by psiemens** [comment]
Thanks for opening this @austinkline!

I've also been thinking about a view like this. If implemented, here's how I think it could be used:

- NFTs prefer typed views for data that is commonly consumed across the ecosystem. Things like titles, descriptions, images and other media. There's benefit in putting this data in strongly-typed standard data structures so that projects can easily consume data from each other programmatically. Call these "primary views."
  - My hope is that as we define more primary views, it becomes easier to express metadata consistently across projects. Marketplaces, etc shouldn't have to rely on application-specific views like `TopShotMomentMetadataView`.
- NFTs use a generic view like `DictView` as a fallback for metadata that doesn't fit into the primary views. Maybe they still have their own domain-specific views (like `TopShotMomentMetadataView`), but they could also return that data in the `DictView`. The advantage is that there's always a way to get _everything_. The disadvantage is that the data is less descriptive than what is provided through primary views.

Lastly it sounds like this is closely related to #74, so I'm thinking about how that design might affect this one.

**Comment by bluesign** [comment]
I know this will be little unorthodox but what if we merge two ( Primary Views and Generic View ) 

Something like : 

```
pub struct MetaRawView {
    pub let data: {String: {String: AnyStruct}}
}
```

which can hold all metadata in a single dictionary, group by a string key. 

With this string key, you can have data required by "Primary Views"  and then we can add some helper functions to contract to construct View from dictionary. 

So if we have a `DisplayView` like: 

```
 pub struct Display {
        pub let name: String
        pub let description: String
        pub let thumbnail: AnyStruct{File}
}
```

We can have "Display" key in the `MetaRawView.data` like:

```
{
"Display": {
  "name: "Amazing NFT",
  "description: "Description",
  "thumbnail": .... 
 }
}
```

and contracts can call helper like: `makeDisplayView(MetaRawView.data["Display"])`


Or we can always use an opposite version, primary views exporting to dictionary.

**Comment by austinkline** [comment]
@psiemens @bluesign  I think we're on the same page here. A `DictView` or something like it would basically serve as the basis for other views. A `DictView` won't be able to answer the question "how do I show this NFT" or anything like that, but it does give a way to ask "what data does this nft contain?". If that is the question this view aims to serve, maybe it should just be called `DataView` or something like that, but I am not picky

@psiemens yes this is also related to #74, I wasn't sure if one was "better" than the other since they both can serve the same use case. My thought would be that you'd first support this kind of broad view since it is applicable to all resources not just NFTs.

**Comment by psiemens** [comment]
> Or we can always use an opposite version, primary views exporting to dictionary.

@bluesign Is this the `toDictionary` option that @austinkline mentioned on #74? I really like that approach. If the core problem to solve is "show me all the data for this NFT", I think it makes a lot of sense for each view to return a generic representation of itself that can be easily serialized to JSON or other formats.

A client could loop over all views on an NFT and merge them into a single dictionary.

Going the other direction (with `MetaRawView`) could be fragile. Some views will have required fields, but what happens if one of those required fields is missing in `MetaRawView` or is the wrong type? There's room for programmer error there, and we lose some of the type safety of Cadence.

**Comment by bluesign** [comment]
@psiemens yes, `toDictionary` option can be also good, but the problem there I am afraid we have to somehow key them on first level with type identifier to prevent collision. ( which can look little not user friendly )

**Comment by joshuahannan** [comment]
I'm gonna close this issue since it was addressed with traits
